// Code generated by piper's step-generator. DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"time"

	"github.com/SAP/jenkins-library/pkg/config"
	"github.com/SAP/jenkins-library/pkg/events"
	"github.com/SAP/jenkins-library/pkg/gcp"
	"github.com/SAP/jenkins-library/pkg/gcs"
	"github.com/SAP/jenkins-library/pkg/log"
	"github.com/SAP/jenkins-library/pkg/piperenv"
	"github.com/SAP/jenkins-library/pkg/splunk"
	"github.com/SAP/jenkins-library/pkg/telemetry"
	"github.com/SAP/jenkins-library/pkg/validation"
	"github.com/bmatcuk/doublestar"
	"github.com/spf13/cobra"
)

type brunoExecuteOptions struct {
	BrunoCollection        string   `json:"brunoCollection,omitempty"`
	RunOptions             []string `json:"runOptions,omitempty"`
	BrunoInstallCommand    string   `json:"brunoInstallCommand,omitempty"`
	BrunoEnvironment       string   `json:"brunoEnvironment,omitempty"`
	BrunoGlobalEnv         string   `json:"brunoGlobalEnv,omitempty"`
	EnvVars                []string `json:"envVars,omitempty"`
	EnvFile                string   `json:"envFile,omitempty"`
	FailOnError            bool     `json:"failOnError,omitempty"`
	Recursive              bool     `json:"recursive,omitempty"`
	Bail                   bool     `json:"bail,omitempty"`
	Parallel               bool     `json:"parallel,omitempty"`
	SandboxMode            string   `json:"sandboxMode,omitempty"`
	CsvFilePath            string   `json:"csvFilePath,omitempty"`
	JSONFilePath           string   `json:"jsonFilePath,omitempty"`
	IterationCount         int      `json:"iterationCount,omitempty"`
	Tags                   string   `json:"tags,omitempty"`
	ExcludeTags            string   `json:"excludeTags,omitempty"`
	TestsOnly              bool     `json:"testsOnly,omitempty"`
	ReporterJSON           string   `json:"reporterJson,omitempty"`
	ReporterJunit          string   `json:"reporterJunit,omitempty"`
	ReporterHtml           string   `json:"reporterHtml,omitempty"`
	ReporterSkipAllHeaders bool     `json:"reporterSkipAllHeaders,omitempty"`
	ReporterSkipHeaders    []string `json:"reporterSkipHeaders,omitempty"`
	Delay                  int      `json:"delay,omitempty"`
	Insecure               bool     `json:"insecure,omitempty"`
}

type brunoExecuteInflux struct {
	step_data struct {
		fields struct {
			bruno bool
		}
		tags struct {
		}
	}
}

func (i *brunoExecuteInflux) persist(path, resourceName string) {
	measurementContent := []struct {
		measurement string
		valType     string
		name        string
		value       interface{}
	}{
		{valType: config.InfluxField, measurement: "step_data", name: "bruno", value: i.step_data.fields.bruno},
	}

	errCount := 0
	for _, metric := range measurementContent {
		err := piperenv.SetResourceParameter(path, resourceName, filepath.Join(metric.measurement, fmt.Sprintf("%vs", metric.valType), metric.name), metric.value)
		if err != nil {
			log.Entry().WithError(err).Error("Error persisting influx environment.")
			errCount++
		}
	}
	if errCount > 0 {
		log.Entry().Error("failed to persist Influx environment")
	}
}

type brunoExecuteReports struct {
}

func (p *brunoExecuteReports) persist(stepConfig brunoExecuteOptions, gcpJsonKeyFilePath string, gcsBucketId string, gcsFolderPath string, gcsSubFolder string) {
	if gcsBucketId == "" {
		log.Entry().Info("persisting reports to GCS is disabled, because gcsBucketId is empty")
		return
	}
	log.Entry().Info("Uploading reports to Google Cloud Storage...")
	content := []gcs.ReportOutputParam{
		{FilePattern: "**/TEST-*.xml", ParamRef: "", StepResultType: "acceptance-test"},
		{FilePattern: "**/TEST-*.html", ParamRef: "", StepResultType: "acceptance-test"},
		{FilePattern: "**/requirement.mapping", ParamRef: "", StepResultType: "requirement-mapping"},
		{FilePattern: "**/delivery.mapping", ParamRef: "", StepResultType: "delivery-mapping"},
	}

	gcsClient, err := gcs.NewClient(gcpJsonKeyFilePath, "")
	if err != nil {
		log.Entry().Errorf("creation of GCS client failed: %v", err)
		return
	}
	defer gcsClient.Close()
	structVal := reflect.ValueOf(&stepConfig).Elem()
	inputParameters := map[string]string{}
	for i := 0; i < structVal.NumField(); i++ {
		field := structVal.Type().Field(i)
		if field.Type.String() == "string" {
			paramName := strings.Split(field.Tag.Get("json"), ",")
			paramValue, _ := structVal.Field(i).Interface().(string)
			inputParameters[paramName[0]] = paramValue
		}
	}
	if err := gcs.PersistReportsToGCS(gcsClient, content, inputParameters, gcsFolderPath, gcsBucketId, gcsSubFolder, doublestar.Glob, os.Stat); err != nil {
		log.Entry().Errorf("failed to persist reports: %v", err)
	}
}

// BrunoExecuteCommand Installs Bruno CLI and executes specified Bruno API collections.
func BrunoExecuteCommand() *cobra.Command {
	const STEP_NAME = "brunoExecute"

	metadata := brunoExecuteMetadata()
	var stepConfig brunoExecuteOptions
	var startTime time.Time
	var influx brunoExecuteInflux
	var reports brunoExecuteReports
	var logCollector *log.CollectorHook
	var splunkClient *splunk.Splunk
	telemetryClient := &telemetry.Telemetry{}

	var createBrunoExecuteCmd = &cobra.Command{
		Use:   STEP_NAME,
		Short: "Installs Bruno CLI and executes specified Bruno API collections.",
		Long:  `This script executes [Bruno](https://www.usebruno.com/) API tests from a collection via the [Bruno CLI](https://docs.usebruno.com/bru-cli/overview) command line tool.`,
		PreRunE: func(cmd *cobra.Command, _ []string) error {
			startTime = time.Now()
			log.SetStepName(STEP_NAME)
			log.SetVerbose(GeneralConfig.Verbose)

			GeneralConfig.GitHubAccessTokens = ResolveAccessTokens(GeneralConfig.GitHubTokens)

			path, err := os.Getwd()
			if err != nil {
				return err
			}
			fatalHook := &log.FatalHook{CorrelationID: GeneralConfig.CorrelationID, Path: path}
			log.RegisterHook(fatalHook)

			err = PrepareConfig(cmd, &metadata, STEP_NAME, &stepConfig, config.OpenPiperFile)
			if err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			// Set step error patterns for improved error detection
			stepErrors := make([]log.StepError, len(metadata.Metadata.Errors))
			for i, err := range metadata.Metadata.Errors {
				stepErrors[i] = log.StepError{
					Pattern:  err.Pattern,
					Message:  err.Message,
					Category: err.Category,
				}
			}
			log.SetStepErrors(stepErrors)

			if len(GeneralConfig.HookConfig.SentryConfig.Dsn) > 0 {
				sentryHook := log.NewSentryHook(GeneralConfig.HookConfig.SentryConfig.Dsn, GeneralConfig.CorrelationID)
				log.RegisterHook(&sentryHook)
			}

			if len(GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 || len(GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
				splunkClient = &splunk.Splunk{}
				logCollector = &log.CollectorHook{CorrelationID: GeneralConfig.CorrelationID}
				log.RegisterHook(logCollector)
			}

			if err = log.RegisterANSHookIfConfigured(GeneralConfig.CorrelationID); err != nil {
				log.Entry().WithError(err).Warn("failed to set up SAP Alert Notification Service log hook")
			}

			validation, err := validation.New(validation.WithJSONNamesForStructFields(), validation.WithPredefinedErrorMessages())
			if err != nil {
				return err
			}
			if err = validation.ValidateStruct(stepConfig); err != nil {
				log.SetErrorCategory(log.ErrorConfiguration)
				return err
			}

			return nil
		},
		Run: func(_ *cobra.Command, _ []string) {
			vaultClient := config.GlobalVaultClient()
			if vaultClient != nil {
				defer vaultClient.MustRevokeToken()
			}

			stepTelemetryData := telemetry.CustomData{}
			stepTelemetryData.ErrorCode = "1"
			handler := func() {
				influx.persist(GeneralConfig.EnvRootPath, "influx")
				reports.persist(stepConfig, GeneralConfig.GCPJsonKeyFilePath, GeneralConfig.GCSBucketId, GeneralConfig.GCSFolderPath, GeneralConfig.GCSSubFolder)
				config.RemoveVaultSecretFiles()
				stepTelemetryData.Duration = fmt.Sprintf("%v", time.Since(startTime).Milliseconds())
				stepTelemetryData.ErrorCategory = log.GetErrorCategory().String()
				stepTelemetryData.PiperCommitHash = GitCommit
				telemetryClient.SetData(&stepTelemetryData)
				telemetryClient.LogStepTelemetryData()
				if len(GeneralConfig.HookConfig.SplunkConfig.Dsn) > 0 {
					splunkClient.Initialize(GeneralConfig.CorrelationID,
						GeneralConfig.HookConfig.SplunkConfig.Dsn,
						GeneralConfig.HookConfig.SplunkConfig.Token,
						GeneralConfig.HookConfig.SplunkConfig.Index,
						GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if len(GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint) > 0 {
					splunkClient.Initialize(GeneralConfig.CorrelationID,
						GeneralConfig.HookConfig.SplunkConfig.ProdCriblEndpoint,
						GeneralConfig.HookConfig.SplunkConfig.ProdCriblToken,
						GeneralConfig.HookConfig.SplunkConfig.ProdCriblIndex,
						GeneralConfig.HookConfig.SplunkConfig.SendLogs)
					splunkClient.Send(telemetryClient.GetData(), logCollector)
				}
				if GeneralConfig.HookConfig.GCPPubSubConfig.Enabled {
					log.Entry().Debug("publishing event to GCP Pub/Sub...")
					// prepare event payload
					payload := events.NewPayloadTaskRunFinished(
						telemetryClient.GetData().StageName,
						STEP_NAME,
						stepTelemetryData.ErrorCode,
					)
					// create event
					eventData, err := events.NewEventTaskRunFinished(
						GeneralConfig.HookConfig.GCPPubSubConfig.TypePrefix,
						GeneralConfig.HookConfig.GCPPubSubConfig.Source,
						payload,
					)
					// publish cloud event via GCP Pub/Sub
					err = gcp.NewGcpPubsubClient(
						vaultClient,
						GeneralConfig.HookConfig.GCPPubSubConfig.ProjectNumber,
						GeneralConfig.HookConfig.GCPPubSubConfig.IdentityPool,
						GeneralConfig.HookConfig.GCPPubSubConfig.IdentityProvider,
						GeneralConfig.CorrelationID,
						GeneralConfig.HookConfig.OIDCConfig.RoleID,
					).Publish(
						fmt.Sprintf("%spipelinetaskrun-finished", GeneralConfig.HookConfig.GCPPubSubConfig.TopicPrefix),
						eventData,
					)
					if err != nil {
						log.Entry().WithError(err).Warn("event publish failed")
					}
				}
			}
			log.DeferExitHandler(handler)
			defer handler()
			telemetryClient.Initialize(STEP_NAME)
			brunoExecute(stepConfig, &stepTelemetryData, &influx)
			stepTelemetryData.ErrorCode = "0"
			log.Entry().Info("SUCCESS")
		},
	}

	addBrunoExecuteFlags(createBrunoExecuteCmd, &stepConfig)
	return createBrunoExecuteCmd
}

func addBrunoExecuteFlags(cmd *cobra.Command, stepConfig *brunoExecuteOptions) {
	cmd.Flags().StringVar(&stepConfig.BrunoCollection, "brunoCollection", os.Getenv("PIPER_brunoCollection"), "Path to the Bruno collection directory (containing bruno.json).")
	cmd.Flags().StringSliceVar(&stepConfig.RunOptions, "runOptions", []string{`run`, `{{.BrunoCollection}}`, `--reporter-junit`, `target/bruno/TEST-{{.CollectionDisplayName}}.xml`, `--reporter-html`, `target/bruno/TEST-{{.CollectionDisplayName}}.html`}, "The Bruno CLI run options. Supports Go templating with variables like {{.BrunoCollection}} and {{.CollectionDisplayName}}.")
	cmd.Flags().StringVar(&stepConfig.BrunoInstallCommand, "brunoInstallCommand", `npm install @usebruno/cli --global --quiet`, "The shell command to install Bruno CLI.")
	cmd.Flags().StringVar(&stepConfig.BrunoEnvironment, "brunoEnvironment", os.Getenv("PIPER_brunoEnvironment"), "Bruno environment name to use for the collection run (--env).")
	cmd.Flags().StringVar(&stepConfig.BrunoGlobalEnv, "brunoGlobalEnv", os.Getenv("PIPER_brunoGlobalEnv"), "Bruno global/workspace-level environment name (--global-env).")
	cmd.Flags().StringSliceVar(&stepConfig.EnvVars, "envVars", []string{}, "Environment variable overrides in key=value format (--env-var). Can be specified multiple times.")
	cmd.Flags().StringVar(&stepConfig.EnvFile, "envFile", os.Getenv("PIPER_envFile"), "Path to environment file (.bru or .json) to use for the collection run (--env-file).")
	cmd.Flags().BoolVar(&stepConfig.FailOnError, "failOnError", true, "Defines the behavior in case tests fail. When set to true, the step will fail if any test fails.")
	cmd.Flags().BoolVar(&stepConfig.Recursive, "recursive", false, "Run requests recursively in subdirectories (-r).")
	cmd.Flags().BoolVar(&stepConfig.Bail, "bail", false, "Stop execution after a failure of a request, test, or assertion (--bail).")
	cmd.Flags().BoolVar(&stepConfig.Parallel, "parallel", false, "Run requests in parallel (--parallel). Default is sequential execution.")
	cmd.Flags().StringVar(&stepConfig.SandboxMode, "sandboxMode", `safe`, "JavaScript sandbox mode - \"safe\" (default) or \"developer\" (--sandbox).")
	cmd.Flags().StringVar(&stepConfig.CsvFilePath, "csvFilePath", os.Getenv("PIPER_csvFilePath"), "Path to CSV file for data-driven testing (--csv-file-path).")
	cmd.Flags().StringVar(&stepConfig.JSONFilePath, "jsonFilePath", os.Getenv("PIPER_jsonFilePath"), "Path to JSON data file for data-driven testing (--json-file-path).")
	cmd.Flags().IntVar(&stepConfig.IterationCount, "iterationCount", 0, "Number of times to run the collection (--iteration-count).")
	cmd.Flags().StringVar(&stepConfig.Tags, "tags", os.Getenv("PIPER_tags"), "Only run requests that have ALL of the specified tags, comma-separated (--tags).")
	cmd.Flags().StringVar(&stepConfig.ExcludeTags, "excludeTags", os.Getenv("PIPER_excludeTags"), "Skip requests that have ANY of the specified tags, comma-separated (--exclude-tags).")
	cmd.Flags().BoolVar(&stepConfig.TestsOnly, "testsOnly", false, "Only run requests that have tests or active assertions (--tests-only).")
	cmd.Flags().StringVar(&stepConfig.ReporterJSON, "reporterJson", os.Getenv("PIPER_reporterJson"), "Path to generate a JSON report (--reporter-json).")
	cmd.Flags().StringVar(&stepConfig.ReporterJunit, "reporterJunit", os.Getenv("PIPER_reporterJunit"), "Path to generate a JUnit report (--reporter-junit). Supports Go templating.")
	cmd.Flags().StringVar(&stepConfig.ReporterHtml, "reporterHtml", os.Getenv("PIPER_reporterHtml"), "Path to generate an HTML report (--reporter-html). Supports Go templating.")
	cmd.Flags().BoolVar(&stepConfig.ReporterSkipAllHeaders, "reporterSkipAllHeaders", false, "Skip all headers in the report (--reporter-skip-all-headers).")
	cmd.Flags().StringSliceVar(&stepConfig.ReporterSkipHeaders, "reporterSkipHeaders", []string{}, "Skip specific headers in the report (--reporter-skip-headers).")
	cmd.Flags().IntVar(&stepConfig.Delay, "delay", 0, "Delay between each request in milliseconds (--delay).")
	cmd.Flags().BoolVar(&stepConfig.Insecure, "insecure", false, "Allow insecure server connections (--insecure).")

	cmd.MarkFlagRequired("brunoCollection")
}

// retrieve step metadata
func brunoExecuteMetadata() config.StepData {
	var theMetaData = config.StepData{
		Metadata: config.StepMetadata{
			Name:        "brunoExecute",
			Aliases:     []config.Alias{},
			Description: "Installs Bruno CLI and executes specified Bruno API collections.",
		},
		Spec: config.StepSpec{
			Inputs: config.StepInputs{
				Resources: []config.StepResources{
					{Name: "tests", Type: "stash"},
				},
				Parameters: []config.StepParameters{
					{
						Name:        "brunoCollection",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   true,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_brunoCollection"),
					},
					{
						Name:        "runOptions",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "[]string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     []string{`run`, `{{.BrunoCollection}}`, `--reporter-junit`, `target/bruno/TEST-{{.CollectionDisplayName}}.xml`, `--reporter-html`, `target/bruno/TEST-{{.CollectionDisplayName}}.html`},
					},
					{
						Name:        "brunoInstallCommand",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `npm install @usebruno/cli --global --quiet`,
					},
					{
						Name:        "brunoEnvironment",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_brunoEnvironment"),
					},
					{
						Name:        "brunoGlobalEnv",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_brunoGlobalEnv"),
					},
					{
						Name:        "envVars",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "[]string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     []string{},
					},
					{
						Name:        "envFile",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_envFile"),
					},
					{
						Name:        "failOnError",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     true,
					},
					{
						Name:        "recursive",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name:        "bail",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name:        "parallel",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name:        "sandboxMode",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     `safe`,
					},
					{
						Name:        "csvFilePath",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_csvFilePath"),
					},
					{
						Name:        "jsonFilePath",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_jsonFilePath"),
					},
					{
						Name:        "iterationCount",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "int",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     0,
					},
					{
						Name:        "tags",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_tags"),
					},
					{
						Name:        "excludeTags",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_excludeTags"),
					},
					{
						Name:        "testsOnly",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name:        "reporterJson",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_reporterJson"),
					},
					{
						Name:        "reporterJunit",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_reporterJunit"),
					},
					{
						Name:        "reporterHtml",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     os.Getenv("PIPER_reporterHtml"),
					},
					{
						Name:        "reporterSkipAllHeaders",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
					{
						Name:        "reporterSkipHeaders",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "[]string",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     []string{},
					},
					{
						Name:        "delay",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "int",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     0,
					},
					{
						Name:        "insecure",
						ResourceRef: []config.ResourceReference{},
						Scope:       []string{"PARAMETERS", "STAGES", "STEPS"},
						Type:        "bool",
						Mandatory:   false,
						Aliases:     []config.Alias{},
						Default:     false,
					},
				},
			},
			Containers: []config.Container{
				{Name: "bruno", Image: "node:24-bookworm", WorkingDir: "/home/node"},
			},
			Outputs: config.StepOutputs{
				Resources: []config.StepResources{
					{
						Name: "influx",
						Type: "influx",
						Parameters: []map[string]interface{}{
							{"name": "step_data", "fields": []map[string]string{{"name": "bruno"}}},
						},
					},
					{
						Name: "reports",
						Type: "reports",
						Parameters: []map[string]interface{}{
							{"filePattern": "**/TEST-*.xml", "type": "acceptance-test"},
							{"filePattern": "**/TEST-*.html", "type": "acceptance-test"},
							{"filePattern": "**/requirement.mapping", "type": "requirement-mapping"},
							{"filePattern": "**/delivery.mapping", "type": "delivery-mapping"},
						},
					},
				},
			},
		},
	}
	return theMetaData
}
